### ISSUE TITLE
pull_new.sh/pull_changes.sh: possible changes

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/makeregistry#16]
proposed change:

In `pull_new.sh` we clone down any new repos we don't have yet

In `pull_changes.sh` we just run `git pull`. But, sometimes this leads to conflicts in the existing git repos on the server. 

To avoid any conflicts, we could instead combine pull_new and pull_changes to `git clone --depth 1` all repos, which should add some time overall I guess, but will avoid any git conflicts

**Comment by maelle** [comment]
It makes sense!

**Comment by maelle** [comment]
an issue is that we couldn't use this as a sort of backup of the repos anymore (since we'd only have the latest version), but having a backup might be out of scope for this.

**Comment by sckott** [comment]
true, but i could do that separately on the same server i think - can see if there's enough disk space

**Comment by maelle** [comment]
what changes were made?

**Comment by sckott** [comment]
just hadn't pushed up changes yet

**Comment by sckott** [comment]
now using this https://github.com/ropenscilabs/makeregistry/blob/master/inst/automation/pull_ropensci.sh for ropensci repos and https://github.com/ropenscilabs/makeregistry/blob/master/inst/automation/pull_ropenscilabs.sh for ropenscilabs - and still using https://github.com/ropenscilabs/makeregistry/blob/master/inst/automation/pull_other.sh for other repos

**Comment by maelle** [comment]
Cool, thanks. Does https://github.com/ropenscilabs/makeregistry#automation-files need to be updated?

**Comment by sckott** [comment]
updated
