### ISSUE TITLE
How to add repos that are not in the org

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/makeregistry#17]
Where's the list of repos to clone that are not in the org i.e. peer-reviewed packages that have not been transferred?

And how can editors add a new entry to that list?

**Comment by sckott** [comment]
Hmm, I just do it by hand. there's only 2 right now, so I just git pulled them into the `repos/other/` directory manually. But since we might have more, i guess we need a list of them. I guess just like the exclude_list, we should add another text file with the list of pkgs outside our orgs

**Comment by maelle** [comment]
ok, can you add it or should I?

**Comment by sckott** [comment]
i can

**Comment by maelle** [comment]
thanks

**Comment by sckott** [comment]
added git clone urls instead of names - in #16 we'll rework the work flow, and for these repos we can just have this list of git urls to clone
