### ISSUE TITLE
recent change is causing weird url outcome

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/makeregistry#18]
in recent registry build https://github.com/ropensci/roregistry/commit/b08d48ef0c8970a329dcf19692ac5486f68660e0

a url was wrapped in a list, `"https://github.com/gmbecker/genbankr"` was replaced with `"list(\"https://github.com/gmbecker/genbankr\")"`

**Comment by maelle** [comment]
Not sure how it happened but I can't reproduce it, found another bug in codemetar instead :grimacing: https://github.com/ropenscilabs/makeregistry/pull/19

**Comment by maelle** [comment]
this is now solved I think?

**Comment by sckott** [comment]
i'll take a look

**Comment by sckott** [comment]
looks to be sorted out
