### ISSUE TITLE
How can we put the git URL used for pulling, in the codemeta JSON

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/makeregistry#20]
cc @jeroen 

Currently the JSON building happens in two steps.
1) Pulling/cloning repos using git URLs from a list somewhere. There are three folders: others, ropensci, ropenscilabs where repos are stored.
2) Building JSON from the repos in the three folders using the content of the repos that has been pulled/cloned.

So now 2) doesn't have access to the URLs in 1) for repos in the "others" folder. For repos that are in the ropensci or ropenscilabs folder we do use the folder name for building an URL we are confident about.

https://github.com/ropenscilabs/makeregistry/blob/48ac72b96bd33485b5088110c453c40ecb4ebac6/R/codemeta.R#L32-L36

The URLs in 1) are the most robust. How could we change the workflow to use the URLs used 1)?

**Comment by jeroen** [comment]
Alternatively, perhaps you could generate a separate file in step 1 (along side the codemeta) that only contains the package name and origin (git) url for all packages in our registry. Then we can base the build infra on this information, make sure nothing gets guessed.

**Comment by maelle** [comment]
that sounds smart.

**Comment by sckott** [comment]
> Then we can base the build infra on this information,

do you mean a separate file in the registry repo?

**Comment by maelle** [comment]
@jeroen?

**Comment by jeroen** [comment]
Yes, if that makes it easier to publish the real URL's of the git repositories in our registry.

**Comment by maelle** [comment]
@sckott so could step 1 create a JSON file with just the URLs to the repos?

I don't think it can include package names too? (but anyway they're not often different from the repo part of the URL).

**Comment by sckott** [comment]
yes, i can do that, would need to include pkg name too i think - in most cases repo name is the pkg name, but i get there's some exceptions

**Comment by sckott** [comment]
the `registry_urls.json` file will be created every 5.5 hrs - it runs quickly so can make it more often for sure
