### ISSUE TITLE
Current issues for today

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/makeregistry#21]
Today there are a lot of issues in the registry because of my own PR #14 I think it'll be solved in the next build thanks to https://github.com/ropenscilabs/makeregistry/commit/48ac72b96bd33485b5088110c453c40ecb4ebac6

**Comment by maelle** [comment]
issues = many fields in lists, i.e. still boxed.

**Comment by sckott** [comment]
okay, i still have to install it on the server - doesn't happen automatically 😸

**Comment by maelle** [comment]
Btw we might need to reset the current codemeta at its state from a few days ago before re building otherwise the code will use the current entries... that are wrong.

**Comment by sckott** [comment]
which state is that?

**Comment by maelle** [comment]
Not sure, before you merged my PR that introduced the bugs?

**Comment by maelle** [comment]
@sckott the registry still looked ok in https://github.com/ropensci/roregistry/commit/917c5bdbc297e5d673ebb24ff0a633d3aae01dad I think

**Comment by sckott** [comment]
ok, thanks

**Comment by sckott** [comment]
fixed now
