### ISSUE TITLE
repos without man folders are not considered pkgs

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/makeregistry#22]
[registry_urls.json](https://raw.githubusercontent.com/ropensci/roregistry/gh-pages/registry_urls.json) has 391 pkgs
[registry.json](https://raw.githubusercontent.com/ropensci/roregistry/gh-pages/registry.json) has 387 pkgs 

The 4 pkgs additional in registry_urls.json are:

- codefinch
- datagovau
- httparser
- riris

Those four don't have man folders. this pkg has a filter here  https://github.com/ropenscilabs/makeregistry/blob/master/R/zzz.R#L2 to filter out any repos that don't have man folders. 

So, what do we do? An argument can be made to add these 4 repos to exclude list since they're all unconf projects (i think) that aren't moving anywhere as far as I can tell. Or do we not exclude repos without man folders so that these 4 are included? Or something else?

@maelle @jeroen

**Comment by jeroen** [comment]
If they don't have any documentation they can hardly be considered packages. Let's archive them.

**Comment by sckott** [comment]
ok

**Comment by sckott** [comment]
rebuilt - we now have equal numbers: **387** - only difference is `gendercoder`/`gendercodeR`
