### ISSUE TITLE
Add field "staff_maintained"

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/makeregistry#36]
@sckott according to the curation policy packages mentioned by staff should be marked as such, and there is now a badge for that in the new website design. I think this means packages by you and @jeroen (not sure I can vouch for my packages _as staff_ because of the definition of my tasks :thinking: ).

Cc @noamross

**Comment by sckott** [comment]
(i assume _mentioned_ should be _maintained_?)

I think it can be automated, just by using the maintainer of each pkg against an array of staff names. I think any you maintain @maelle should be included

**Comment by maelle** [comment]
thanks.

I think this should happen at registry creation to allow us to add any exception if needed, and also because we might need the info in other places.

**Comment by sckott** [comment]
https://github.com/ropensci/roregistry/blob/gh-pages/registry.json

**Comment by maelle** [comment]
thank you :pray:
