### ISSUE TITLE
change get_review?

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/makeregistry#7]
I assume since ropensci/onboarding changed to ropensci/software-review that we should change https://github.com/ropenscilabs/makeregistry/blob/master/R/registry.R#L3 to match?

perhaps `grepl("ropensci\\/onboarding|ropensci\\/software-review")`

@maelle

**Comment by maelle** [comment]
right, good catch!! Did it work?

**Comment by sckott** [comment]
yes, though I had to make a change in codemetar as well, see https://github.com/ropensci/codemetar/compare/ropensci-review-badge-detect

**Comment by maelle** [comment]
Have you made a PR to codemetar? Thanks a lot for the fixes!

**Comment by sckott** [comment]
not yet, should I?

**Comment by maelle** [comment]
Yes please

**Comment by sckott** [comment]
do you mind if I merge the change here?

**Comment by maelle** [comment]
No i do not
