### ISSUE TITLE
How to delete repos

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/makeregistry#9]
At the moment I think the mirroring code from the GitHub organization to the server only adds and updates repos, but does not remove them when they have been deleted/transferred, correct @sckott?

@jeroen's `betty` package is therefore still included in the registry although it's been moved to his personal account.

**Comment by sckott** [comment]
Right

**Comment by sckott** [comment]
can make another bash script to check for deleted/moved repos, can you give any more egs?

**Comment by maelle** [comment]
None comes to mind but I'll try to find some.

**Comment by jeroen** [comment]
I've been intending to move `acme` and `agent` to my own repo, because I didn't find the time to get these to the point that I intended.

**Comment by maelle** [comment]
so the workflow now for exclusion is a manually updated txt list, do we want to change that?

**Comment by sckott** [comment]
updating the https://github.com/ropenscilabs/makeregistry/blob/master/inst/automation/exclude_list.txt file now is all that's needed. on the server i now pull down this file and delete those repos that are excluded
